### ISSUE TITLE
Projection code and data added for January meeting

### ISSUE THREAD

**Issue by mwpowers** [bobaekang/icjia-r-user-group#17]
I added 3 files to a folder in the code section. The 3 files are an AOIC aggregate probation caseload data csv, and an Rmarkdown with corresponding html document showing the probation projection I wrote recently. I think the only thing that you need to change in the R code is the location of the AOIC_PopulationData.csv (line 58 in the markdown) to where you download the AOIC file. You can also change this to the url of the csv and that will work as well, depending on how you run the code.

`AOIC <- read_csv("C:/Transfers/201901/AOIC_PopulationData.csv")`

Normally, SPAC would use CHRI data, which I obviously cannot upload. So for this demonstration, I am simulating data that represents CHRI arrests that result in a conviction and probation sentence. This simulation is shown in the R code. There are some pretty ugly plots at the end that I need to improve, so my vote for a future meeting would be a GGplot workshop.

**Comment by bobaekang** [comment]
Thank you @mwpowers for uploading example files!

**A quick note**:
The example directory is now moved under the `meeting/`. [This link will lead to the new location](https://github.com/bobaekang/icjia-r-user-group/tree/master/meeting/20190110_SPAC_projection_example).

A minor collorary to this change is that one should use the following URL to grab the data directly from the URL:

```r
# directly from the url
url <- "https://raw.githubusercontent.com/bobaekang/icjia-r-user-group/master/meeting/20190110_SPAC_projection_example/AOIC_PopulationData.csv"
AOIC <- read_csv(url)
```

Of course, if one downloads the example directory as a whole, the following will suffice since the data file lives on the same (working) directory;
```r
# from the project (working) directory
AOIC <- read_csv("AOIC_PopulationData.csv")
```

Please let me know or leave a comment below if anyone has any questions. Thank you!
