### ISSUE TITLE
Handling dataframes in s4 objects

### ISSUE THREAD

**Issue by kgruschow** [bobaekang/icjia-r-user-group#24]
Does anyone have experience working with dataframes in s4 objects? My basic need is that I want to add specific values (e.g. count per zipcode) into the geographical information dataframe inside the object, while explicitly linking by matched GEOID. 

 for context I am working using the tigris library with the following command:
KG.illinois <- zctas(cb = TRUE, starts_with = c("60","61","62"), year = 2010, state = 'Il')

This pulls down a large spatial object of the s4 type containing the census Zip code areas (ZCTAs), this type also includes an embedded s3 dataframe. 

I can get ggplot to plot the data quite nicely, however effectively only using the internal dataframe. So far I've been using a brute force method of creating an external s3 version of the data frame then moving a column back onto the internal dataframe like this:

KG.illinois@data$Count <- mapfilewcounts$Count

however this seems a bit crude. I've been trying the following based on online tutorial, however it does not work and is frankly beyond my comprehension.
KG.illinois.withLocations <- data_frame(id=rownames(KG.illinois@data), ZCTA5=KG.illinois@data$ZCTA5) %>% left_join(KG.InfoNet.locationsbyear, by "ZCTA5")

**Comment by bobaekang** [comment]
I met with @kgruschow in person to discuss solutions.

Just to share with everyone in the user group, here are some things we talked about and more:

* R S4 objects are an interesting thing that often seems at odds with the rest of the R objects. If you want to more about it, skim through ["S4" chapter of _Advnaced R_ by Hadley Wickham](https://adv-r.hadley.nz/s4.html) as well as [this brief introduction to R's object-oriented programming (OOP) system](https://adv-r.hadley.nz/oo.html) from the same book.

* `SpatialPolygonsDataFrame` class, as well as other `Spatial*DataFrame` classes provided by `sp` package, is an S4 object with `@data`. Here `@data` is a "slot" belongs to a `SpatialPolygonsDataFrame` object. You can think of it as a field or a property of that object--whose content is a dataframe. You can access its content like the following:

```r
# to accesss the data.frame in the "data" slot
s4obj@data

# to access a column named "count" in @data
s4obj@data$count
s4$count # this is a shortcut
```

* As a general practice, it is often useful to organize your code into a set of R functions, each of which "encapsulates" or "abstracts away" a meaningful set of operations you intend to apply to an object. This will allow you to think in terms of higher-level business logic rather than of implementation details.

* Piping with the `%>%` operator can be useful to clearly express the order and flow of higher-level logic applied to your data object. Compare the following two approaches, for example:



* As a related note, it is often useful to treat your original data table as a immutable object. That is, avoid overwriting the object with changes you apply to it. Using functions can help here, since function inputs are almost always kept intact while you can get the result as the function output.
